import { NavBar } from "@/components/navbar.component";
import ArticleProvider from "@/contexts/article.context";
import ThemeProvider from "@/theme/ThemeProvider";
import { Container } from "@mui/material";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ArticleProvider>
            <NavBar />
            <Container maxWidth="lg" sx={{ py: 4 }}>
              {children}
            </Container>
          </ArticleProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
